language: python
python:
  - 3.6
os:
  - linux
git:
  depth: 1
before_install:
  - pip install pip --upgrade
install:
  - pip install -r requirements.txt
script:
  - cookiecutter --no-input . package_name=example
  - cd example
  - pip install -r requirements.dev.txt
  - pip install -e .
  - make style
  - make check_types
  - make test
  - make test.verbose
  - make coverage
  - make docs
  - make dist
  - make dist.test
